version: "3.7"

services:
    app:
        image: node:16
        command:  sh -c "npm start"
        ports:
            - 3000:3000
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - mysqldb:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shop

volumes:
    mysqldb: